### ISSUE TITLE
(On windows) compiled DLLs include hard paths to conda build directories

### ISSUE THREAD

**Issue by tony-p** [conda-forge/openssl-feedstock#146] opened 2023-12-13 10:29 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When trying to generate a certificate using the conda installed package, get the error
```console
> openssl req -x509 -days 1000 -newkey rsa:2048 -keyout my-key.pem -out my-cert.pem

Can't open "D:\bld\openssl_split_1701161630111\_h_env\Library/openssl.cnf" for reading, No such file or directory
8C580000:error:80000003:system library:BIO_new_file:No such process:crypto\bio\bss_file.c:67:calling fopen(D:\bld\openssl_split_1701161630111\_h_env\Library/openssl.cnf, r)
8C580000:error:10000080:BIO routines:BIO_new_file:no such file:crypto\bio\bss_file.c:75:
```

On further inspection of `libcrypto-3-x64.dll` there are 10 occurences of the path "D:\bld\openssl_split_1701161630111\_h_env\Library" some of which reference the `*.cnf` files and further the engine etc

### Installed packages
pixi.lock (`pixi list` doesn't exist (at least in version 0.9.1)
```toml
version: 3
metadata:
  content_hash:
    win-64: e90c2ee71ad70fc0a1c8302029533a7d1498f2bffcd0eaa8d2934700e775dc1d
  channels:
  - url: https://conda.anaconda.org/conda-forge/
    used_env_vars: []
  platforms:
  - win-64
  sources: []
  time_metadata: null
  git_metadata: null
  inputs_metadata: null
  custom_metadata: null
package:
- platform: win-64
  name: ca-certificates
  version: 2023.11.17
  category: main
  manager: conda
  dependencies: []
  url: https://conda.anaconda.org/conda-forge/win-64/ca-certificates-2023.11.17-h56e8100_0.conda
  hash:
    md5: 1163114b483f26761f993c709e65271f
    sha256: c6177e2a4967db7a4e929c6ecd2fafde36e489dbeda23ceda640f4915cb0e877
  build: h56e8100_0
  arch: x86_64
  subdir: win-64
  build_number: 0
  license: ISC
  size: 154700
  timestamp: 1700281021312
- platform: win-64
  name: openssl
  version: 3.2.0
  category: main
  manager: conda
  dependencies:
  - ca-certificates
  - ucrt >=10.0.20348.0
  - vc >=14.2,<15
  - vc14_runtime >=14.29.30139
  url: https://conda.anaconda.org/conda-forge/win-64/openssl-3.2.0-hcfcfb64_1.conda
  hash:
    md5: d10167022f99bad12ee07dea022d5830
    sha256: 373b9671173ef3413d2a95f3781176b818db904ba82298f8447b9658d71e2cc9
  build: hcfcfb64_1
  arch: x86_64
  subdir: win-64
  build_number: 1
  constrains:
  - pyopenssl >=22.1
  license: Apache-2.0
  license_family: Apache
  size: 8248125
  timestamp: 1701164404616
- platform: win-64
  name: ucrt
  version: 10.0.22621.0
  category: main
  manager: conda
  dependencies: []
  url: https://conda.anaconda.org/conda-forge/win-64/ucrt-10.0.22621.0-h57928b3_0.tar.bz2
  hash:
    md5: 72608f6cd3e5898229c3ea16deb1ac43
    sha256: f29cdaf8712008f6b419b8b1a403923b00ab2504bfe0fb2ba8eb60e72d4f14c6
  build: h57928b3_0
  arch: x86_64
  subdir: win-64
  build_number: 0
  constrains:
  - vs2015_runtime >=14.29.30037
  license: LicenseRef-Proprietary
  license_family: PROPRIETARY
  size: 1283972
  timestamp: 1666630199266
- platform: win-64
  name: vc
  version: '14.3'
  category: main
  manager: conda
  dependencies:
  - vc14_runtime >=14.36.32532
  url: https://conda.anaconda.org/conda-forge/win-64/vc-14.3-h64f974e_17.conda
  hash:
    md5: 67ff6791f235bb606659bf2a5c169191
    sha256: 86ae94bf680980776aa761c2b0909a0ddbe1f817e7eeb8b16a1730f10f8891b6
  build: h64f974e_17
  arch: x86_64
  subdir: win-64
  build_number: 17
  track_features: vc14
  license: BSD-3-Clause
  license_family: BSD
  size: 17176
  timestamp: 1688020629925
- platform: win-64
  name: vc14_runtime
  version: 14.36.32532
  category: main
  manager: conda
  dependencies:
  - ucrt >=10.0.20348.0
  url: https://conda.anaconda.org/conda-forge/win-64/vc14_runtime-14.36.32532-hdcecf7f_17.conda
  hash:
    md5: d0de20f2f3fc806a81b44fcdd941aaf7
    sha256: b317d49af32d5c031828e62c08d56f01d9a64cd3f40d4cccb052bc38c7a9e62e
  build: hdcecf7f_17
  arch: x86_64
  subdir: win-64
  build_number: 17
  constrains:
  - vs2015_runtime 14.36.32532.* *_17
  license: LicenseRef-ProprietaryMicrosoft
  license_family: Proprietary
  size: 739437
  timestamp: 1694292382336

```

### Environment info

```shell
$ pixi info
pixi 0.9.1

Platform            : win-64
Virtual packages    : __win=0=0
                    : __cuda=12.0=0
                    : __archspec=1=x86_64
Cache dir           : C:\Users\me\AppData\Local\rattler/cache
Auth storage        : C:\Users\me\.rattler/rattler_auth_store.json
```

**Comment by h-vetinari** [comment] 2023-12-13 10:57
Please provide the requested information from the issue template, in particular the content of the environment (`conda list` / `pixi list`)

**Comment by h-vetinari** [comment] 2023-12-13 11:03
> When trying to generate a certificate using the conda installed package, get the error

Can you provide a reproducer (e.g. in C)?


> On further inspection of `libcrypto-3-x64.dll` there are 10 occurences of the path "D:\bld\openssl_split_1701161630111_h_env\Library"

Comparing the path from the error message with the one from this statement:
```
"D:\bld\openssl_split_1701161630111\_h_env\Library"
"D:\bld\openssl_split_1701161630111_h_env\Library"
                                   ^
                                   missing backslash
```
Assuming this is not just a C&P error - if one of the paths gets corrupted in the build process, it's possible that the "make-builds-relocatable" process fails to cover where that path occurs.

**Comment by tony-p** [comment] 2023-12-13 11:12
> Please provide the requested information from the issue template, in particular the content of the environment (conda list / pixi list)

Added the pixi.lock file, there currently isn't a `conda list` equivalent 

> Can you provide a reproducer (e.g. in C)?

Done

**Comment by tony-p** [comment] 2023-12-13 11:14
I tried a sed replace of the DLL replacing `D:\bld\openssl_split_1701161630111\_h_env` with the expanded `$CONDA_PREFIX`, the error no longer occurs, but I think it now segfaults instead as still don't get the expected follow up steps

**Comment by h-vetinari** [comment] 2024-03-16 11:11
> On further inspection of `libcrypto-3-x64.dll` there are 10 occurences of the path "D:\bld\openssl_split_1701161630111_h_env\Library" some of which reference the `*.cnf` files and further the engine etc

@mbargull there seems to be a problem with relocations here. Do you think this merits a conda-build bug?

**Comment by isuruf** [comment] 2024-05-21 17:13
Should be fixed now

**Comment by h-vetinari** [comment] 2024-05-21 21:49
For reference, by these two PRs: #157 & #165

**Closed** 2024-05-21 21:49 UTC
Labels: bug
